## Ex01

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

## Ex02

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Ex03

In [20]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [21]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

## Ex04

In [22]:
np.cov(a.T)[0, 1]

2.0